name: Test nix workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  nix-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        channel: ["nixos-unstable", "25.11"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Init nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:${{ matrix.channel }}
          # github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - run: nix build
      - run: nix flake check
